####################################################################################
# Repository > Settings > Secrets:
# Bintray
#   BINTRAY_API_KEY   : API KEY for Bintray uploading.
#   BINTRAY_GPG_PASS  : Signing key for Bintray uploading.
####################################################################################
name: assemble Android library aar
on:
  - push
jobs:
  assemble-android-library-artifacts:
    runs-on: ubuntu-20.04
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    env:
      _JAVA_OPTIONS: "-Xmx4g -Dfile.encoding=UTF-8"
      TZ: Asia/Tokyo
      BINTRAY_API_KEY: ${{secrets.BINTRAY_API_KEY}}
      BINTRAY_GPG_PASS: ${{secrets.BINTRAY_GPG_PASS}}
    steps:
      - uses: actions/checkout@v2.0.0
      - name: "cache / gradle"
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: "environments / java"
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: "environments / android / sdk"
        uses: malinskiy/action-android/install-sdk@release/0.1.0
      - name: "environments / android / PATH"
        run: |
          export EXTRA_PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/ndk-bundle:$PATH
          echo "path=$EXTRA_PATH" >> $GITHUB_ENV
      - name: "environments"
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "PWD=$PWD"
          echo "PATH=$path"
          echo "java `java -version`: `which java`"
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "sdkmanager=`which sdkmanager`"
          gradle -v
          ls -al
      - name: "android / test / format"
        run: |
          ./gradlew format
          if [ "`git diff | grep '.kt'`" != "" ]; then
            echo "kotlin format error"
            echo "run -> ./gradlew format"
            exit 1
          fi
      - name: "android / test / codes"
        run: |
          ./gradlew \
            testDebugUnitTest \
            assembleRelease
      - name: "android / publish / test-results"
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: "android / publish / bintray"
        run: |
          ./gradlew bintrayUpload
